--EJERCICIO 1
SELECT * FROM PUBLIC.MOVIES;

--EJERCICIO 2
SELECT * FROM GENRES;

--EJERCICIO 3
SELECT * FROM PUBLIC.STUDIOS WHERE STUDIO_ACTIVE = 1;

--EJERCICIO 4
SELECT * FROM PUBLIC.MEMBERS 
ORDER BY MEMBER_DISCHARGE_DATE DESC LIMIT 20;


--EJERCICIO 5

--EJERCICIO 6
SELECT MOVIE_NAME, MOVIE_LAUNCH_DATE FROM PUBLIC.MOVIES
WHERE 
YEAR(MOVIE_LAUNCH_DATE) >= '2000'
AND 
MOVIE_NAME LIKE 'A%'
ORDER BY MOVIE_LAUNCH_DATE DESC;

--EJERCICIO 7


--EJERCICIO 8

--EJERCICIO 9
SELECT 
DIRECTOR_NAME, AGE
FROM 
(
SELECT 
DIRECTOR_NAME, DATEDIFF(YEAR, DIRECTOR_BIRTH_DATE, TODAY()) AS AGE,
DIRECTOR_DEAD_DATE
FROM DIRECTORS
)
WHERE AGE <= 50
AND DIRECTOR_DEAD_DATE IS NULL;

--EJERCICIO 10
SELECT 
ACTOR_NAME, AGE
FROM 
(
SELECT 
ACTOR_NAME, DATEDIFF(YEAR, ACTOR_BIRTH_DATE, TODAY()) AS AGE,
ACTOR_DEAD_DATE
FROM ACTORS
)
WHERE AGE < 50
AND ACTOR_DEAD_DATE IS NOT NULL;
